### ISSUE TITLE
Feature request: `yalc watch`

### ISSUE THREAD

**Issue by tbredin** [whitecolor/yalc#22]
Would be amazing to have a `yalc watch` script that automatically watches your package during development, and essentially runs a `yalc push` on changes. 

My use case: Currently running `yalc push` manually when I have made a significant change that I want to test in my main application (where it is linked)

Potentially this just watches the whole package, or perhaps could specify a key file or folder to watch, eg: `yalc watch src/index.js`

What do you think?

**Comment by whitecolor** [comment]
Hi, there was discussion about such requests https://github.com/whitecolor/yalc/issues/15

You can use something like `nodemon -x 'yalc push'`

I actually would not use this, but make more consistent changes to the package, then push it. If i'm actively developing the code that is used in the app, I maked it a part of the app first, then take it out into separate package.

**Comment by christopherthielen** [comment]
If you build your packages using webpack, this is a simple recipe you can use.  This watches the upstream package and auto-pushes (to downstream) after each webpack build:

`yarn add -D yalc webpack-shell-plugin`

package.json:
```
  "scripts": {
    "watch": "npm run clean && WATCH=true YALC=true webpack --progress",
```

webpack.config.js:

```
const ShellPlugin = require("webpack-shell-plugin");
const postBuildScript = process.env.YALC === 'true' ? 'npx yalc push' : 'true';
... 
   watch: process.env.WATCH === "true",
   plugins: [
      new ShellPlugin({ onBuildExit: postBuildScript }),
   ],
```

then:

`~/upstreampkg $ npm run watch`

**Comment by matdru** [comment]
I came here looking for such a feature, but in the end turns our I didn't need it. My current setup involves a UI library that I have as a separate repo, bundled with rollup.js in watch mode, then i have a nodemon that watches the output directory of rollup for changes and fires yalc push, finally, i have my actual app running with hot reloading. I can have all of those running at the same time, any change to the UI project gets pushed through this pipeline to my app in <2s. I'm actually thinking about writing a post about this setup, it works like magic.

**Comment by sanboxrunner** [comment]
Hello!

I'm bumping this idea because even though there are use cases where I could see this being inessential, there certainly are use cases where having a yalc watch would be extremely useful. For example, I am the primary developer of a Language Server, which has implementations in various clients; the Language Server, therefore, needs to be a separate package from each client, which also means a separate repo. Previously, things were a mess of copy file paths and manually starting servers. Yalc has simplified that significantly, and the only thing that would make it better would be a yalc watch. I currently use nodemon to simulate a yalc watch, but it isn't ideal.

I am very willing to put in the work to properly create this feature, if I could be pointed in the right direction to start.

**Comment by whitecolor** [comment]
Did you try to use existing watching solutions like nodemon -x 'yalc push'?

If you need something more custom you can easily create it on your own using some watching library. I don't see a reason to add such functionality to yalc itself.

**Comment by sanboxrunner** [comment]
I did and it works, but if one tries (like I am) to not require other devs to add anything to their PATH (the software is complicated enough as is, I don't need to scare off potential contributors with a confusing setup) then you end up creating a watch script like this:
```json
		"testWatch": "concurrently --kill-others \"tsc --watch\" \"yalc publish && nodemon --exec npm run dev\"",
		"dev": "yalc push"
```
Which you know, hey that works, but it's still quite a confusing mess. Additionally, it watch compiles initially very strangely where error pop up as the watch slowly compiles, only to be erased as the compile finishes. Which is fine, but it catches people a bit off-guard.

Anywho, it's your repo and you seem determined. I've got a solution, albeit a messy one.

**Comment by bitflower** [comment]
@matdru can you elaborate a bit more? Using `rollup` too....

**Comment by whitecolor** [comment]
There is also `publish/push --changed` flag was added that will publish only if the content of the package has really changed comparing to published version

**Comment by aleclarson** [comment]
@whitecolor Why wouldn't `--changed` be the default?

**Comment by whitecolor** [comment]
> @whitecolor Why wouldn't `--changed` be the default?

Don't see the big reason to do it by default for manual publish.

**Comment by pie6k** [comment]
I don't think it's resolved issue, while it's possible to use nodemon, it's not always fitting (eg. if you use typescript or some sort of other files like html/css/yaml etc files.

Each of those might require some custom setup, which takes development time.

I think something like `yalc watch` could work like

1. It'd watch current folder for changes (maybe only files not listed in .npmignore etc)
2. after every file change it'd run `yarn publish`
3. it could potentially rebuild the package
4. you'd be able to instantly check new changes in connected project

While I appreciate this package, I think it'd be very useful.

If you have to iterate a lot on some package before you're happy with the result - difference between 5s vs 30s of each iteration (and avoiding 20mins-1h of manual setup of watching files) is a big deal that could result in actually either keeping some package alive or making it slowly stale and dead because you'd prefer to workaround something rather then work on package with slow iteration speed / being aware you need some custom setup to improve iteration time

**Comment by bennodev19** [comment]
You can also update your yalc package by using `tsc-watch` and the `onSuccess` flag.
https://www.npmjs.com/package/tsc-watch

package.json
```
// ..
"scripts": {
    "dev-watch": "tsc-watch --onSuccess \"yalc push\""
  }
// ..
```

This works for me and hopefully also for you ;D

**Comment by adnan-razzaq** [comment]
nodemon --watch dist --exec \"yalc push \"

**Comment by RicardoBrito1938** [comment]
> nodemon --watch dist --exec "yalc push "

works smoothly, cheers

**Comment by kitze** [comment]
If you're using `tsup` you can do 
```
"dev": "tsup --watch --onSuccess \"yalc push\""
```

**Comment by TSMMark** [comment]
I had great success with https://github.com/e-dant/watcher, avoiding having to run node to do the file watching.

Installed via `brew install watcher`, the resulting script could probably be optimized, but here's what I got so far and I've been using it all day.

```bash
#!/bin/bash

watcher="/opt/homebrew/bin/tw"

echo "Watching package for changes..."
yalc="$(yarn global bin)/yalc"

include_patterns="d2/src"
exclude_patterns=".yalc"

$watcher | while read -r event; do
  should_handle_event=false

  for pattern in $include_patterns; do
    if [[ "$event" == *"$pattern"* ]]; then
      should_handle_event=true
      break
    fi
  done

  if [ "$should_handle_event" = false ]; then
    # TODO: ENV verbose flag to log this.
    continue
  fi

  for pattern in $exclude_patterns; do
    if [[ "$event" == *"$pattern"* ]]; then
      should_handle_event=false
      break
    fi
  done

  if [ "$should_handle_event" = false ]; then
    # TODO: ENV verbose flag to log this.
    continue
  fi

  echo "Pushing linked package update because code changed: $event"

  $yalc push --sig --changed || echo "Yalc push failed... Sometimes this can happen if a file was deleted or moved. Continuing to watch for changes..."
done
```

This watcher package somehow uses extremely little CPU or RAM. I'm guessing it relies on filesystem events to avoid polling.

<img width="556" alt="Image" src="https://github.com/user-attachments/assets/4cd1c32a-f1b6-47fa-a239-bc3874f1c1a8" />
