### ISSUE TITLE
`yalc remove` removes modules it shouldn't from `node_modules`

### ISSUE THREAD

**Issue by erikphansen** [whitecolor/yalc#38]
If you use `yalc add` and later use `yalc remove` to clean up, instead of just restoring the consuming app's `package.json` back to normal and removing the `.yalc` dir from the consuming app, it also removes a the corresponding package from `node_modules`.

## Expected behavior
When using `yalc remove` after doing a `yalc add`, it shouldn't be touching anything in the consuming app's `node_modules` at all. It should just restore the changes it made to `package.json` and remove the files it added to `.yalc`.

**Comment by whitecolor** [comment]
Hi, `yarn/npm unlink` doesn't restore your node_modules, you have to run `yarn/npm` after that, If i'm not mistaken.

**Comment by wickkidd** [comment]
As @erikphansen stated, in a project that is _not_ using workspaces, when using `yalc remove` after a `yalc add` (not a `yalc link`) it removes the corresponding package from `node_modules`. Why is yalc even touching `node_modules` in this case? Again, I'm _not_ talking about removing a `yalc link`.

**Comment by wclr** [comment]
> I only want to remove the "yalc" copy of the package — not the one in node_modules.

But `yalc add package` command copies the content to node_modules, it is not even linking it. So to restore `npm install` should be run to restore the content that should be instead of yalced package.

**Comment by wickkidd** [comment]
Wow. Sure enough, it's doing that (copying the yalc'd package to node_modules _in addition_ to `.yalc`). Why? According to [the documentation](https://github.com/wclr/yalc#add), `yalc add` copies the package to `.yalc` which it then points to in the `package.json` with a `file:.yalc/my-package`. This would seem to negate having to copy it additionally to node_modules. Am I missing something? How is it using both copies of the yalc'd package?

Currently I am having to `cp -r node_modules/my-package tmp` before `yalc add` and then `cp -r tmp node_modules/my-package && rm -rf tmp` after `yalc remove` in a script because it's faster than npm/yarn install. I'd really like to not have to do this if possible.

For some context, I have written a script in `my-package` that allows a dev to have yalc add it to any number of specified consuming apps, starts a watcher which calls `yalc push --changed` on changes to src files and then when the process is quit by the dev, it does a `yalc remove` in the specified apps. This allows a dev to do everything yalc-related from `my-package` including the clean up. This reduces cognitive load for the team.

**Comment by wclr** [comment]
> This would seem to negate having to copy it additionally to node_modules. Am I missing something? How is it using both copies of the yalc'd package?

Well yes it copies the content when you run update.. maybe not, I forgot. Need to see the code. :D

**Comment by wclr** [comment]
When you add with `--pure` doesn't` touch `package.json` or `node_modules`, it is used for workspaces mode.

> it turns out that we don't want the package inside the node_modules folder to be overwritten.

So then I don't get why you need yalced package then?

**Comment by wickkidd** [comment]
I'd rather not use `pure` in my use case. What I'd like to do is this:

`yalc add my-package` which in the destination would put `{ "my-package": "file:./.yalc/my-package" }` in the `package.json` and copy the actual package files to `./yalc`. Both of these currently happen. I would like it _not_ to additionally copy the package files to `node_modules`. This requires me to npm/yarn install when I'm done which should be unnecessary to get back to the state before using yalc. How are the package files from `.yalc` _and_ `node_modules` being used at the same time anyway? It seems to me that only one can be used at a time which should be the ones in `.yalc`. If not, then why have a `.yalc` folder in the first place? Is what I'm trying to suggest making sense?

**Comment by wclr** [comment]
What package manager you are using?

> This requires me to npm/yarn install when I'm done which should be unnecessary to get back to the state before using yalc. 

This is necessary because package dependencies may differ, and need to be reinstalled.

> If not, then why have a .yalc folder in the first place? Is what I'm trying to suggest making sense?

We keep a "local" copy of a package content, the package can be reinstalled from it or linked (in case of `link:` for yarn or npm which uses symlinks for file: protocol). I don't get what you are trying to suggest yet.

**Comment by wickkidd** [comment]
Ah, never mind. yalc isn't doing this. [npm is](https://github.com/npm/using-pkgs-docs/pull/7/files). I don't often use `file:` for the version in `package.json` so I hadn't noticed that it actually gets copied to node_modules instead of just being used wherever the reference points. Wow. That was unexpected without an npm install or update. Sorry to have taken your time. At least the next person will understand why this is happening.
