### ISSUE TITLE
No version option/command

### ISSUE THREAD

**Issue by chocolateboy** [whitecolor/yalc#53]
It looks like a new version was released [4 days ago](https://www.npmjs.com/package/yalc/v/1.0.0-pre.25) [1], but there's no way to check if a currently-installed version is up-to-date without figuring out where it's installed and checking its `package.json`:

```bash
$ yalc --version
Use `yalc help` to see available commands.

$ yalc version
Unknown commmand `version`. Use `yalc help` to see available commands.

$ yalc help | grep -i version || echo "no version"
no version
```

[1] To NPM, but not (yet?) in Git. Please consider adding and pushing tags for these so they show up [here](https://github.com/whitecolor/yalc/releases).

**Comment by aleclarson** [comment]
This feature was added 12 days ago. See here: 18bfaae8d6f47a3cda8da59b5b70a68f56707568

@whitecolor Need help closing issues?

While on the topic of versions, Yalc should start using normal versioning instead of the `-pre.` suffix. And it would be great to get `semantic-release` setup. LMK if you want help with that, @whitecolor!
